packages:
  - "packages/*"

overrides:
  brace-expansion@>=2.0.0 <2.1.7: ^2.1.7
  js-yaml@>=3.0.0 <3.15.2: ^3.15.2
  js-yaml@>=4.0.0 <4.3.2: ^4.3.2
  minimatch@>=9.0.0 <9.0.7: ^9.0.7
  nanoid@<3.3.18: ^3.3.18
  picomatch@<2.3.2: ^2.3.2
  postcss@<8.5.23: ^8.5.23
  rollup@>=4.0.0 <4.59.0: ^4.59.0
  shell-quote@<1.9.0: ^1.9.0
  source-map-js@>=1.0.0 <1.2.2: ^1.2.2
